language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4.1

before_script:
  - cd spec/dummy
  - bundle exec rake db:migrate db:test:prepare
  - cd ../../

gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile

matrix:
  exclude:
    - rvm: 2.1
      gemfile: gemfiles/5.0.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/3.2.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/4.0.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/4.1.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/4.2.gemfile
